openapi: 3.0.0
info:
  title: JOB-API
  version: 1.0.0
servers:
  - url: https://jobs-api-20oi.onrender.com/api/v1
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  schemas:
    RegisterUser:
      type: object
      properties:
        name:
          type: string
          example: victoria
        email:
          type: string
          example: victoria@example.com
        password:
          type: string
          example: secretpassword
    LoginUser:
      type: object
      properties:
        email:
          type: string
          example: tim1@gmail.com
        password:
          type: string
          example: omafetim
    Job:
      type: object
      properties:
        company:
          type: string
          example: amanda cp
        position:
          type: string
          example: cosmetics
tags:
  - name: Auth
  - name: Jobs
paths:
  /auth/register:
    post:
      tags:
        - Auth
      summary: Register a new user
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegisterUser'
      responses:
        '201':
          description: Successful registration
          content:
            application/json: {}
  /auth/login:
    post:
      tags:
        - Auth
      summary: Log in
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginUser'
      responses:
        '200':
          description: Successful login
          content:
            application/json: {}
  /jobs:
    post:
      tags:
        - Jobs
      summary: Create a new job
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Job'
      security:
        - bearerAuth: []
      responses:
        '201':
          description: Job created successfully
          content:
            application/json: {}
    get:
      tags:
        - Jobs
      summary: Get all jobs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of jobs
          content:
            application/json: {}
  /jobs/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: Job ID
    get:
      tags:
        - Jobs
      summary: Get a job by ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Job details
          content:
            application/json: {}
    patch:
      tags:
        - Jobs
      summary: Update a job by ID
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Job'
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Job updated
          content:
            application/json: {}
    delete:
      tags:
        - Jobs
      summary: Delete a job by ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Job deleted
          content:
            application/json: {}
